export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const TOGGLE_CART_HIDDEN = 'TOGGLE_CART_HIDDEN';
export const ADD_ITEM = 'ADD_ITEM';
export const CLEAR_ITEM = 'CLEAR_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const UPDATE_COLLECTIONS_SUCCESS = 'UPDATE_COLLECTIONS_SUCCESS';
export const UPDATE_COLLECTIONS_ERROR = 'UPDATE_COLLECTIONS_ERROR';
export const UPDATE_COLLECTIONS_REQUEST = 'UPDATE_COLLECTIONS_REQUEST';
